'use client'
import {useMemo,useState} from 'react'
import Link from 'next/link'
import {content,topics} from '@/lib/content'

function Highlight({text,query}:{text:string,query:string}){if(!query)return text;const index=text.toLowerCase().indexOf(query.toLowerCase());if(index<0)return text;return <>{text.slice(0,index)}<mark>{text.slice(index,index+query.length)}</mark>{text.slice(index+query.length)}</>}
export default function Search(){
  const [q,setQ]=useState('');const [type,setType]=useState('All');const [topic,setTopic]=useState('All');const [sort,setSort]=useState('relevance')
  const results=useMemo(()=>content.filter(x=>(type==='All'||x.type===type)&&(topic==='All'||x.topic===topic)&&(`${x.title} ${x.excerpt} ${x.topic}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='newest'?b.date.localeCompare(a.date):(q&&b.title.toLowerCase().includes(q.toLowerCase())?1:0)-(q&&a.title.toLowerCase().includes(q.toLowerCase())?1:0)),[q,type,topic,sort])
  return <><header className="page-hero shell"><div className="eyebrow">Knowledge search</div><h1>Search</h1><p>Search research, frameworks, glossary terms, brands and topics.</p></header><section className="search-panel shell"><label htmlFor="site-search">Search the research platform</label><input id="site-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Try ‘Community Gravity’" autoFocus/><div className="filter-row" aria-label="Filter results by content type">{['All','Research','Scorecard','Case Study','Framework','Benchmark','Weekly'].map(x=><button type="button" className={type===x?'active':''} aria-pressed={type===x} onClick={()=>setType(x)} key={x}>{x}</button>)}</div><div className="search-options"><label htmlFor="topic-filter">Topic<select id="topic-filter" value={topic} onChange={event=>setTopic(event.target.value)}><option>All</option>{topics.map(value=><option key={value}>{value}</option>)}</select></label><label htmlFor="sort-results">Sort<select id="sort-results" value={sort} onChange={event=>setSort(event.target.value)}><option value="relevance">Relevance</option><option value="newest">Newest</option></select></label></div><h2 className="results-heading">{q?`Results for “${q}”`:'All research'}</h2><p aria-live="polite">{results.length} {results.length===1?'result':'results'}</p>{results.length?<div className="search-results">{results.map(x=><article key={x.slug}><div className="eyebrow">{x.type}{x.topic?` · ${x.topic}`:''}</div><h3><Link href={`/${x.slug}`}><Highlight text={x.title} query={q}/></Link></h3><p><Highlight text={x.excerpt} query={q}/></p></article>)}</div>:<div className="empty-state"><h3>No matching research</h3><p>Try a broader phrase, choose All content types, or explore the <Link href="/glossary">Community Intelligence Glossary</Link>.</p></div>}</section></>
}
