import {defineType,defineField,defineArrayMember} from 'sanity'
import {commonFields,bodyField} from './shared'

const doc=(name:string,title:string,extra:ReturnType<typeof defineField>[]=[])=>(defineType as any)({name,title,type:'document',fields:[...commonFields.slice(0,-1),...extra,bodyField],preview:{select:{title:'title',subtitle:'excerpt',media:'coverImage'}}})
export const article=doc('article','Article')
export const researchReport=doc('researchReport','Research report',[defineField({name:'executiveSummary',type:'text'}),defineField({name:'methodology',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'keyFindings',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'dataLimitations',type:'text'}),defineField({name:'researchPeriod',type:'string'}),defineField({name:'sources',type:'array',of:[defineArrayMember({type:'url'})]}),defineField({name:'download',type:'file'})])
export const scorecard=doc('scorecard','Community Intelligence Scorecard',[
  defineField({name:'brandName',type:'string',validation:r=>r.required()}),
  defineField({name:'criteria',title:'Nine criterion scores',type:'scorecardCriteria',validation:r=>r.required()}),
  defineField({name:'overallScore',type:'number',description:'Calculated from the nine criteria. Do not edit independently.',readOnly:true,validation:r=>r.required().integer().min(0).max(100)}),
  defineField({name:'rating',type:'string',description:'Calculated from the overall score.',readOnly:true,validation:r=>r.required(),options:{list:['Exceptional','Excellent','Strong','Developing','Mixed','At Risk']}}),
  defineField({name:'assessmentStatus',type:'string',initialValue:'Editorial Community Intelligence assessment'}),
  defineField({name:'criterionAnalysis',type:'object',fields:[
    defineField({name:'brandTrust',title:'Brand Trust analysis',type:'text'}),defineField({name:'productSatisfaction',title:'Product Satisfaction analysis',type:'text'}),defineField({name:'innovationPerception',title:'Innovation Perception analysis',type:'text'}),defineField({name:'communityEngagement',title:'Community Engagement analysis',type:'text'}),defineField({name:'advocacy',title:'Advocacy analysis',type:'text'}),defineField({name:'narrativeConsistency',title:'Narrative Consistency analysis',type:'text'}),defineField({name:'competitivePosition',title:'Competitive Position analysis',type:'text'}),defineField({name:'customerSupport',title:'Customer Support analysis',type:'text'}),defineField({name:'aiSearchReadiness',title:'AI Search Readiness analysis',type:'text'}),
  ]}),
  defineField({name:'methodologyVersion',type:'string',initialValue:'Nine criterion methodology'}),defineField({name:'confidence',type:'string',options:{list:['low','medium','high']}}),defineField({name:'keyInsight',type:'text'}),defineField({name:'primaryStrength',type:'text'}),defineField({name:'primaryRisk',type:'text'}),defineField({name:'recommendations',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'dataLimitations',type:'text'})
])
export const caseStudy=doc('caseStudy','Case study',[defineField({name:'subject',type:'string'}),defineField({name:'industry',type:'string'}),defineField({name:'challenge',type:'text'}),defineField({name:'communityDynamics',type:'text'}),defineField({name:'keyLessons',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'businessImplications',type:'text'})])
export const framework=doc('framework','Framework',[defineField({name:'canonicalDefinition',type:'text',validation:r=>r.required()}),defineField({name:'whyItMatters',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'howItWorks',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'example',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'whenToUse',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'createdByRedditrepreneur',type:'boolean',initialValue:true}),defineField({name:'firstPublishedAt',type:'datetime'})])
export const benchmark=doc('benchmark','Benchmark',[defineField({name:'category',type:'string'}),defineField({name:'measurementPeriod',type:'string'}),defineField({name:'sampleDefinition',type:'text'}),defineField({name:'methodology',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'benchmarkFigures',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'value',type:'number'}),defineField({name:'unit',type:'string'})]})]}),defineField({name:'limitations',type:'text'})])
export const weekly=doc('weekly','Community Intelligence Weekly',[defineField({name:'issueNumber',type:'number',validation:r=>r.required().integer().positive()}),defineField({name:'issueDate',type:'date'}),defineField({name:'headlines',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'deepDive',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'communityIntelligenceInsight',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'researchRadar',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'opportunityOfTheWeek',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'whatIAmWatching',type:'array',of:[defineArrayMember({type:'block'})]})])
export const indexIssue=doc('indexIssue','Community Intelligence Index',[defineField({name:'issue',type:'string'}),defineField({name:'brandsOrSectors',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'rankings',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'rank',type:'number'}),defineField({name:'name',type:'string'}),defineField({name:'movement',type:'number'})]})]}),defineField({name:'methodology',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'keyMovements',type:'array',of:[defineArrayMember({type:'string'})]})])
export const glossaryEntry=doc('glossaryEntry','Glossary entry',[defineField({name:'term',type:'string',validation:r=>r.required()}),defineField({name:'conciseDefinition',type:'text',validation:r=>r.required()}),defineField({name:'fullDefinition',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'whyItMatters',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'example',type:'array',of:[defineArrayMember({type:'block'})]}),defineField({name:'relatedTerms',type:'array',of:[defineArrayMember({type:'reference',to:[{type:'glossaryEntry'}]})]})])
export const newsBrief=doc('newsBrief','News brief',[defineField({name:'sourcePublication',type:'string'}),defineField({name:'sourceUrl',type:'url'}),defineField({name:'eventDate',type:'date'}),defineField({name:'whyItMatters',type:'text'}),defineField({name:'communityIntelligenceImplication',type:'text'})])
export const author=defineType({name:'author',title:'Author',type:'document',fields:[defineField({name:'name',type:'string',validation:r=>r.required()}),defineField({name:'slug',type:'slug',options:{source:'name'},validation:r=>r.required()}),defineField({name:'role',type:'string'}),defineField({name:'bio',type:'text'}),defineField({name:'expertise',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'photo',type:'image',options:{hotspot:true},fields:[defineField({name:'alt',type:'string',validation:r=>r.required()})]}),defineField({name:'socialLinks',type:'array',of:[defineArrayMember({type:'url'})]})]})
export const topic=defineType({name:'topic',title:'Topic',type:'document',fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),defineField({name:'slug',type:'slug',options:{source:'title'},validation:r=>r.required()}),defineField({name:'introduction',type:'text',validation:r=>r.required()}),defineField({name:'seo',type:'seo'})]})
export const page=doc('page','Page')
export const siteSettings=defineType({name:'siteSettings',title:'Site settings',type:'document',fields:[defineField({name:'title',type:'string',initialValue:'The Redditrepreneur Research'}),defineField({name:'featuredContent',type:'reference',to:[{type:'article'},{type:'researchReport'},{type:'scorecard'},{type:'caseStudy'},{type:'framework'},{type:'benchmark'},{type:'weekly'}]}),defineField({name:'homepageCollections',type:'array',of:[defineArrayMember({type:'reference',to:[{type:'article'},{type:'researchReport'},{type:'scorecard'},{type:'caseStudy'},{type:'framework'},{type:'benchmark'},{type:'weekly'}]})]}),defineField({name:'newsletterUrl',type:'url'}),defineField({name:'platformUrl',type:'url'}),defineField({name:'auditUrl',type:'url'}),defineField({name:'navigation',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'href',type:'string'})]})]})]})
export const redirect=defineType({name:'redirect',title:'Redirect',type:'document',fields:[defineField({name:'source',type:'string',description:'Path beginning with /',validation:r=>r.required()}),defineField({name:'destination',type:'string',description:'Canonical path or approved external URL',validation:r=>r.required()}),defineField({name:'permanent',type:'boolean',initialValue:true}),defineField({name:'reason',type:'string'})]})
