import Link from 'next/link'
import {ContentCard} from '@/components/cards'
import {Newsletter} from '@/components/newsletter'
import {content, frameworks, topics,latestWeeklySlug} from '@/lib/content'
import {site} from '@/lib/site'
import {withCoverImages} from '@/lib/covers'
import {LatestResearch} from '@/components/latest-research'
import Image from 'next/image'
import {scorecardPillars} from '@/lib/community-intelligence-scorecard'

export default async function Home() {
  const illustrated=await withCoverImages(content.slice(0,7))
  return <>
    <section className="hero shell"><div><div className="eyebrow">The Redditrepreneur Research</div><h1>Understand the Conversations Shaping Brands, Markets and Culture</h1><p>Original Community Intelligence research, frameworks, scorecards and analysis from The Redditrepreneur.</p><div className="actions"><Link className="button" href="/research">Explore the Latest Research</Link><a className="text-link" href={`${site.main}/community-intelligence`}>Learn About Community Intelligence</a></div></div><div className="signal-visual" aria-label="Abstract visual showing conversations becoming intelligence"><span>CONVERSATIONS</span><i></i><span>CONSENSUS</span><i></i><span>INTELLIGENCE</span></div></section>
    <section className="section shell featured-research-section"><div className="section-heading"><div><div className="eyebrow">Featured research</div><h2>The latest thinking in Community Intelligence</h2></div></div><ContentCard item={illustrated[0]} featured/></section>
    <section className="section shell latest-research-section"><div className="section-heading"><div><div className="eyebrow">Research library</div><h2>Latest research</h2></div><Link href="/research">View all research</Link></div><LatestResearch items={illustrated.slice(1,7)}/></section>
    <section className="scorecard-band"><div className="shell split"><div><div className="eyebrow light">Measurement</div><h2>Community Intelligence Scorecards</h2><p>The Redditrepreneur Community Intelligence Scorecard assesses brands across nine criteria grouped into three pillars: Perception, Participation and Strategic Value.</p><Link className="button light-button" href="/the-redditrepreneur-community-intelligence-scorecard">Read the methodology</Link></div><div className="score-preview"><strong>9</strong><span>criteria across three pillars</span><ol>{Object.values(scorecardPillars).sort((a,b)=>a.order-b.order).map(pillar=><li key={pillar.name}>{pillar.name}</li>)}</ol></div></div></section>
    <section className="section shell"><div className="section-heading"><div><div className="eyebrow">Original thinking</div><h2>The Frameworks Defining Community Intelligence</h2></div><Link href="/frameworks">Explore the library</Link></div><div className="framework-grid">{frameworks.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></div>)}</div></section>
    <section className="weekly section"><div className="shell split"><Image className="weekly-image" src="/community-intelligence-weekly-platform-live.png" width={1280} height={720} alt="Community Intelligence Weekly edition announcing that The Redditrepreneur Community Intelligence Platform is live."/><div><div className="eyebrow">Latest issue</div><h2>Community Intelligence Weekly: The Platform Is Live and the Vision Is Becoming Real</h2><p>The Community Intelligence Platform is live, new frameworks are helping explain how online narratives form, and The Redditrepreneur is becoming a complete Community Intelligence company.</p><div className="actions"><Link className="button" href={`/${latestWeeklySlug}`}>Read latest</Link><Link className="text-link" href="/community-intelligence-weekly">Browse archive</Link><a className="text-link" href={site.newsletter}>Subscribe</a></div></div></div></section>
    <section className="section shell"><div className="section-heading"><div><div className="eyebrow">Applied research</div><h2>Case studies and benchmarks</h2></div></div><p className="collection-note">See what brands, products and cultural events reveal about community behaviour, then compare those patterns through transparent benchmark research.</p><div className="card-grid">{illustrated.filter(item=>item.type==='Case Study'||item.type==='Benchmark').slice(0,3).map(item=><ContentCard key={item.slug} item={item}/>)}</div><div className="actions"><Link className="text-link" href="/case-studies">Browse case studies</Link><Link className="text-link" href="/benchmarks">Explore benchmarks</Link></div></section>
    <section className="section shell"><div className="section-heading"><div><div className="eyebrow">Explore by subject</div><h2>Topics</h2></div></div><div className="topic-grid">{topics.map(x=><Link key={x} href={`/topics/${x.toLowerCase().replaceAll(' ','-')}`}>{x}<span>→</span></Link>)}</div></section>
    <section className="section shell glossary-teaser"><div><div className="eyebrow">Glossary</div><h2>Learn the Language of Community Intelligence</h2><p>Clear definitions for the concepts, frameworks and measures shaping this emerging discipline.</p><Link className="button" href="/glossary">Browse the glossary</Link></div><dl><div><dt>Community Intelligence</dt><dd>The practice of analysing authentic online conversations to uncover the beliefs, behaviours and signals influencing markets.</dd></div><div><dt>Share of Consensus</dt><dd>A measure of how strongly a brand or idea appears within trusted community recommendations.</dd></div></dl></section>
    <section className="about-band"><div className="shell split"><div><div className="eyebrow">About the research</div><h2>From conversation to competitive advantage</h2></div><div><p>The Redditrepreneur combines original research, software and professional services to help organisations understand what online communities say about their brand, competitors and market.</p><div className="actions"><a className="text-link" href={site.main}>Main website</a><a className="text-link" href={site.app}>Explore the platform</a><a className="text-link" href={site.audit}>Community Intelligence Audit</a></div></div></div></section>
    <div className="shell"><Newsletter/></div>
  </>
}
