import Image from 'next/image'
import Link from 'next/link'
import type {ContentItem} from '@/lib/content'
import {Newsletter} from './newsletter'
import {site} from '@/lib/site'
import {sanitiseImportedHtml} from '@/lib/sanitise'

export function ArticlePage({item,embedded=false,bodyHtml,coverImageUrl}:{item:ContentItem,embedded?:boolean,bodyHtml?:string,coverImageUrl?:string}){return <article>
  {!embedded&&<><header className="article-header shell"><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={`/${item.type.toLowerCase().replaceAll(' ','-')}s`}>{item.type}</Link></nav><div className="eyebrow">{item.type}</div><h1>{item.title}</h1><p className="dek">{item.excerpt}</p><div className="byline"><Image src="/tonte-bo-douglas.jpg" width={48} height={48} alt="Tonte Bo Douglas"/><span>By <Link href="/authors/tonte-bo-douglas">Tonte Bo Douglas</Link><small>Published <time dateTime={item.date}>{new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date(item.date))}</time> · 8 min read</small></span></div></header>{coverImageUrl?<div className="article-image shell"><Image src={coverImageUrl} width={1600} height={900} alt={item.title} priority/></div>:<div className="article-cover"><div className="eyebrow light">The Redditrepreneur Research</div><strong>{item.title}</strong></div>}</>}
  <div className="article-layout shell"><aside><strong>On this page</strong><a href="#article-content">Article</a><a href="#about-author">About the author</a></aside><div id="article-content" className="prose">{bodyHtml?<div className="legacy-content" dangerouslySetInnerHTML={{__html:sanitiseImportedHtml(bodyHtml)}}/>:<><h2>Overview</h2><p>{item.excerpt}</p><p>This item is awaiting final editorial conversion from the migration source.</p></>}<div className="inline-cta"><h3>Turn conversations into clarity</h3><p>Explore the Community Intelligence platform or commission a focused audit of your brand, competitors and market.</p><div className="actions"><a className="button" href={site.app}>Explore the Platform</a><a className="text-link" href={site.audit}>Learn About the Audit</a></div></div></div></div>
  <section id="about-author" className="author-box shell"><Image src="/tonte-bo-douglas.jpg" width={150} height={150} alt="Tonte Bo Douglas"/><div><div className="eyebrow">About the author</div><h2>Tonte Bo Douglas</h2><p>Founder of The Redditrepreneur and a Community Intelligence researcher and strategist studying how online communities shape trust, discovery, brands and markets.</p><Link href="/authors/tonte-bo-douglas">View Tonte’s latest work</Link></div></section><div className="shell"><Newsletter/></div>
</article>}
