import Image from 'next/image'
import Link from 'next/link'
import type {ContentItem} from '@/lib/content'
import {Newsletter} from './newsletter'
import {site} from '@/lib/site'

export function ArticlePage({item,embedded=false}:{item:ContentItem,embedded?:boolean}){
  return <article>
    {!embedded&&<><header className="article-header shell"><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={`/${item.type.toLowerCase().replaceAll(' ','-')}s`}>{item.type}</Link></nav><div className="eyebrow">{item.type}</div><h1>{item.title}</h1><p className="dek">{item.excerpt}</p><div className="byline"><Image src="/tonte-bo-douglas.jpg" width={48} height={48} alt="Tonte Bo Douglas"/><span>By <Link href="/authors/tonte-bo-douglas">Tonte Bo Douglas</Link><small>Published <time dateTime={item.date}>{new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date(item.date))}</time> · 8 min read</small></span></div></header><div className="article-cover"><div className="eyebrow light">The Redditrepreneur Research</div><strong>{item.title}</strong></div></>}
    <div className="article-layout shell"><aside><strong>On this page</strong><a href="#overview">Overview</a><a href="#why-it-matters">Why it matters</a><a href="#community-intelligence-take">The Community Intelligence take</a></aside><div className="prose"><p className="migration-note"><strong>Migration preview:</strong> The complete historical article body will populate here from the approved Ghost import. This template is displaying preserved metadata and the new editorial treatment.</p><h2 id="overview">Overview</h2><p>{item.excerpt}</p><p>The Redditrepreneur analyses authentic online conversations to understand the beliefs, behaviours and signals influencing brands, competitors and markets.</p><blockquote>Businesses collect data. Community-led businesses collect understanding.</blockquote><h2 id="why-it-matters">Why it matters</h2><p>Community conversations reveal context that conventional dashboards often miss: why customers choose, what creates trust, where expectations are changing and which narratives are becoming consensus.</p><h2 id="community-intelligence-take">The Community Intelligence take</h2><p>This publication forms part of a connected research system. Related concepts, frameworks and evidence will be selected editorially and strengthened by explainable topic relationships.</p><div className="inline-cta"><h3>Turn conversations into clarity</h3><p>Explore the Community Intelligence platform or commission a focused audit of your brand, competitors and market.</p><div className="actions"><a className="button" href={site.app}>Explore the Platform</a><a className="text-link" href={site.audit}>Learn About the Audit</a></div></div></div></div>
    <section className="author-box shell"><Image src="/tonte-bo-douglas.jpg" width={150} height={150} alt="Tonte Bo Douglas"/><div><div className="eyebrow">About the author</div><h2>Tonte Bo Douglas</h2><p>Founder of The Redditrepreneur and a Community Intelligence researcher and strategist studying how online communities shape trust, discovery, brands and markets.</p><Link href="/authors/tonte-bo-douglas">View Tonte’s latest work</Link></div></section><div className="shell"><Newsletter/></div>
  </article>
}
