import Image from 'next/image'
import Link from 'next/link'
import type {ContentItem} from '@/lib/content'
import {Newsletter} from './newsletter'
import {site} from '@/lib/site'
import {prepareImportedHtml} from '@/lib/sanitise'
import {SharePost} from './share-post'
import {content} from '@/lib/content'

export function ArticlePage({item,embedded=false,bodyHtml,coverImageUrl}:{item:ContentItem,embedded?:boolean,bodyHtml?:string,coverImageUrl?:string}){
  const prepared=bodyHtml?prepareImportedHtml(bodyHtml):null
  const related=content.filter(candidate=>candidate.slug!==item.slug&&(candidate.topic===item.topic||candidate.type===item.type)).slice(0,3)
  const archiveHref:Record<ContentItem['type'],string>={Research:'/research',Scorecard:'/scorecards','Case Study':'/case-studies',Framework:'/frameworks',Benchmark:'/benchmarks',Weekly:'/community-intelligence-weekly',Index:'/community-intelligence-index',Article:'/research'}
  return <article id="top">
  {!embedded&&<><header className="article-header shell"><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={archiveHref[item.type]}>{item.type}</Link></nav><div className="eyebrow">{item.type}</div><h1>{item.title}</h1><p className="dek">{item.excerpt}</p><div className="byline"><Image src="/tonte-bo-douglas.jpg" width={48} height={48} alt="Tonte Bo Douglas"/><span>By <Link href="/authors/tonte-bo-douglas">Tonte Bo Douglas</Link><small>Published <time dateTime={item.date}>{new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date(item.date))}</time> · 8 min read</small></span></div></header>{coverImageUrl?<div className="article-image shell"><Image src={coverImageUrl} width={1600} height={900} alt={item.title} priority/></div>:<div className="article-cover"><div className="eyebrow light">The Redditrepreneur Research</div><strong>{item.title}</strong></div>}</>}
  <div className="article-layout shell"><aside><strong>On this page</strong>{prepared?.headings.filter(h=>h.level===2).slice(0,12).map(h=><a href={`#${h.id}`} key={h.id}>{h.label}</a>)}<a className="back-top" href="#top">Back to top</a></aside><div id="article-content" className="prose">{prepared?<div className="legacy-content" dangerouslySetInnerHTML={{__html:prepared.html}}/>:<><h2>Overview</h2><p>{item.excerpt}</p><p>This item is awaiting final editorial conversion from the migration source.</p></>}<div className="inline-cta"><h3>Turn conversations into clarity</h3><p>{item.type==='Scorecard'?'Learn how a focused Community Intelligence Audit can reveal the forces shaping your brand.':'Explore the Community Intelligence platform or commission a focused audit of your brand, competitors and market.'}</p><div className="actions"><a className="button" href={item.type==='Scorecard'?site.audit:site.app}>{item.type==='Scorecard'?'Learn About a Community Intelligence Audit':'Explore the Community Intelligence Platform'}</a><a className="text-link" href={item.type==='Scorecard'?'/the-redditrepreneur-community-intelligence-scorecard':site.audit}>{item.type==='Scorecard'?'Read the methodology':'Learn About the Audit'}</a></div></div></div></div>
  {related.length>0&&<section className="related-content shell" aria-labelledby={`related-${item.slug}`}><div className="eyebrow">Continue exploring</div><h2 id={`related-${item.slug}`}>Related Community Intelligence research</h2><div className="related-grid">{related.map(candidate=><article key={candidate.slug}><div className="eyebrow">{candidate.type}</div><h3><Link href={`/${candidate.slug}`}>{candidate.title}</Link></h3><p>{candidate.excerpt}</p></article>)}</div></section>}
  <div className="shell share-shell"><SharePost title={item.title} url={`${site.url}/${item.slug}/`}/></div>
  <section id="about-author" className="author-box shell"><Image src="/tonte-bo-douglas.jpg" width={150} height={150} alt="Tonte Bo Douglas"/><div><div className="eyebrow">About the author</div><h2>Tonte Bo Douglas</h2><p>Founder of The Redditrepreneur and a Community Intelligence researcher and strategist studying how online communities shape trust, discovery, brands and markets.</p><Link href="/authors/tonte-bo-douglas">View Tonte’s latest work</Link></div></section><div className="shell"><Newsletter/></div>
</article>}
