import Link from 'next/link'
import {ArticlePage} from './article-page'
import Image from 'next/image'
import type {ContentItem} from '@/lib/content'
const dimensions=[
  ['Community Presence','How visible, relevant and meaningfully represented the brand is within the communities that shape its market.'],
  ['Community Trust','The confidence communities place in the brand, its behaviour and the claims made on its behalf.'],
  ['Share of Consensus','How consistently the brand appears within trusted recommendations and repeated community agreement.'],
  ['Insight Responsiveness','How effectively the brand recognises, interprets and responds to meaningful community insight.'],
  ['Community Authority','The degree of credibility and influence the brand holds within relevant community conversations.'],
] as const
export function ScorecardPage({item,bodyHtml,coverImageUrl}:{item:ContentItem,bodyHtml?:string,coverImageUrl?:string}){return <><section className="scorecard-hero"><div className="shell"><nav aria-label="Breadcrumb"><Link href="/">Home</Link> / <Link href="/scorecards">Scorecards</Link></nav><div className="eyebrow light">Community Intelligence Scorecard</div><h1>{item.title}</h1><p>{item.excerpt}</p><div className="score-status"><strong>Editorial assessment</strong><span>This is an editorial Community Intelligence assessment produced by The Redditrepreneur. It is not an automated live SaaS score.</span></div></div></section>{coverImageUrl&&<div className="article-image shell"><Image src={coverImageUrl} width={1600} height={900} alt={item.title} priority/></div>}<section className="section shell"><div className="section-heading"><div><div className="eyebrow">Structured assessment</div><h2>Five dimensions of Community Intelligence</h2></div></div><div className="dimension-grid">{dimensions.map(([name,description],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{description}</p></article>)}</div><div className="methodology-callout"><h2>How This Score Was Calculated</h2><p>The report explains the research approach, evidence considered, research period, limitations and confidence available when the assessment was published.</p><Link className="text-link" href="/the-redditrepreneur-community-intelligence-scorecard">Read the full Scorecard methodology</Link></div></section><ArticlePage item={item} embedded bodyHtml={bodyHtml} coverImageUrl={coverImageUrl}/></>}
