import {notFound} from 'next/navigation'
import {ArticlePage} from '@/components/article-page'
import {ScorecardPage} from '@/components/scorecard-page'
import {FrameworkPage} from '@/components/framework-page'
import {content,latestWeeklyLegacySlug,latestWeeklySlug} from '@/lib/content'
import {client} from '@/sanity/lib/client'
import {site} from '@/lib/site'

export function generateStaticParams(){return content.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=content.find(x=>x.slug===slug);return item?{title:item.title,description:item.excerpt,alternates:{canonical:`/${slug}`},openGraph:{type:'article',title:item.title,description:item.excerpt,url:`/${slug}`,publishedTime:new Date(item.date).toISOString()},twitter:{card:'summary_large_image',title:item.title,description:item.excerpt}}:{}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=content.find(x=>x.slug===slug);if(!item)notFound();const cmsSlug=slug===latestWeeklySlug?latestWeeklyLegacySlug:slug;let cms:{bodyHtml?:string,coverImageUrl?:string}|null=null;try{cms=await client.fetch(`*[_type in ["article","researchReport","scorecard","caseStudy","framework","benchmark","weekly","indexIssue","newsBrief"] && slug.current==$slug][0]{"bodyHtml":body[0].html,"coverImageUrl":coverImage.asset->url}`,{slug:cmsSlug})}catch(error){console.error('Sanity article query failed',error)}const coverImageUrl=item.image||cms?.coverImageUrl;const schema={'@context':'https://schema.org','@type':item.type==='Scorecard'||item.type==='Benchmark'?'Report':'Article',headline:item.title,description:item.excerpt,datePublished:item.date,author:{'@type':'Person',name:'Tonte Bo Douglas',url:`${site.url}/authors/tonte-bo-douglas`},publisher:{'@type':'Organization',name:'The Redditrepreneur',url:site.main},mainEntityOfPage:`${site.url}/${slug}`,image:coverImageUrl};const page=item.type==='Scorecard'?<ScorecardPage item={item} bodyHtml={cms?.bodyHtml} coverImageUrl={coverImageUrl}/>:item.type==='Framework'?<FrameworkPage item={item} bodyHtml={cms?.bodyHtml} coverImageUrl={coverImageUrl}/>:<ArticlePage item={item} bodyHtml={cms?.bodyHtml} coverImageUrl={coverImageUrl}/>;return <>{page}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/></>}
