import fs from 'node:fs'
import {createClient} from '@sanity/client'
import path from 'node:path'
import {arg,ensureDir,mapping,readExport,reportPath,resolveGhostUrl,sanitiseHtml} from './core'
const file=arg('--file');if(!file)throw new Error('Usage: npm run ghost:dry-run -- --file=<export.json>');const dry=process.argv.includes('--dry-run');const {data}=readExport(file);const metas=new Map(data.posts_meta.map(x=>[x.post_id,x]));const author=data.users[0];
const documents=data.posts.map(post=>{const map=mapping(post),meta=metas.get(post.id);return {_id:`ghost-${post.id}`,_type:map.proposed_content_type,title:post.title,slug:{_type:'slug',current:post.slug},excerpt:post.custom_excerpt||post.plaintext?.slice(0,240),publishedAt:post.published_at,updatedAt:post.updated_at,featured:Boolean(post.featured),seo:{_type:'seo',title:meta?.meta_title,description:meta?.meta_description,canonicalUrl:post.canonical_url},legacy:{_type:'legacyMetadata',ghostId:post.id,ghostUuid:post.uuid,originalSlug:post.slug,originalUrl:`https://blog.theredditrepreneur.com/${post.slug}/`,manualReview:map.manual_review,migrationNotes:map.manual_review?['Content type requires editorial review']:[]},coverImageSource:resolveGhostUrl(post.feature_image),body:[{_type:'legacyHtml',_key:'legacy-body',html:sanitiseHtml((post.html||'').replaceAll('__GHOST_URL__','https://blog.theredditrepreneur.com')),reviewStatus:'required'}]}})
const payload=[{_id:`ghost-author-${author.id}`,_type:'author',name:author.name,slug:{_type:'slug',current:author.slug},role:'Founder, Community Intelligence researcher and strategist',bio:'Tonte Bo Douglas is the founder of The Redditrepreneur. His work examines how online communities shape trust, discovery, brands and markets.'},...documents];const out=reportPath(dry?'ghost-dry-run.ndjson':'ghost-import.ndjson');fs.writeFileSync(out,payload.map(x=>JSON.stringify(x)).join('\n')+'\n');const dataDir=path.resolve('data');ensureDir(dataDir);fs.writeFileSync(path.join(dataDir,'migrated-content.json'),JSON.stringify(data.posts.map(post=>{const map=mapping(post);return {title:post.title,slug:post.slug,type:map.proposed_content_type,excerpt:post.custom_excerpt||post.plaintext?.replace(/\s+/g,' ').trim().slice(0,260)||'',date:post.published_at?.slice(0,10)||'2026-01-01',topic:map.proposed_primary_topic}}),null,2));
if(dry){console.log(JSON.stringify({mode:'dry-run',documents:payload.length,output:out,manualReview:documents.filter(x=>x.legacy.manualReview).length},null,2));process.exit(0)}
const projectId=process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,dataset=process.env.NEXT_PUBLIC_SANITY_DATASET||'development',token=process.env.SANITY_API_WRITE_TOKEN;if(!projectId||!token)throw new Error('NEXT_PUBLIC_SANITY_PROJECT_ID and SANITY_API_WRITE_TOKEN are required');const client=createClient({projectId,dataset,token,apiVersion:process.env.NEXT_PUBLIC_SANITY_API_VERSION||'2026-07-12',useCdn:false});let tx=client.transaction();for(const doc of payload)tx=tx.createOrReplace(doc as any);await tx.commit();console.log(JSON.stringify({mode:'import',documents:payload.length,dataset,output:out},null,2))
